name: Cross-Platform Electron Build

on:
  push:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Force Git to use HTTPS instead of SSH
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build for macOS (${{ matrix.arch }})
        run: yarn make --arch=${{ matrix.arch }}

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.arch }}
          path: out/make/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Force Git to use HTTPS instead of SSH
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build for Linux
        run: yarn make

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: out/make/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Force Git to use HTTPS instead of SSH
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build for Windows
        run: yarn make

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          path: out/make/
